name: Publish Terraform Module

on:
  push:
    tags:
      - "v*.*.*"
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  MODULE_NAME: monorepoModuleA
  MODULE_VERSION: ${GITHUB_REF#refs/tags/v} #remove the prefix v
  # MODULES: ["monorepoModuleA", "monorepoModuleB", "monorepoModuleC"]
  # MODULE_VERSION: "0.0.1"
  TFX_DOWNLOAD: "https://github.com/straubt1/tfx/releases/download/v0.1.3/tfx_Linux_x86_64.tar.gz"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print version
        run: echo "Module Version to Publish - ${{ env.MODULE_VERSION }}"
      - name: Download TFX
        run: |
          curl -L -o /usr/local/tfx.tar.gz ${{ env.TFX_DOWNLOAD }}
          tar -xzf /usr/local/tfx.tar.gz
          sudo mv tfx /usr/local/bin/
          tfx -v
      - name: Create Configuration
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          TFE_ORGANIZATION: ${{ secrets.TFE_ORGANIZATION }}
        run: |
          cat <<EOF > ~/.tfx.hcl
          tfeToken = "$TFE_TOKEN"
          tfeOrganization = "$TFE_ORGANIZATION"
          EOF
      - name: Inject Commit SHA into README.md
        run: |
          REPO_URL="${{ github.server_url }}/${{ github.repository }}/tree/$(git rev-parse --abbrev-ref HEAD)"
          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/$(git rev-parse HEAD)"
          README_CONTENT=$(cat <<EOF
          [Repository]($REPO_URL)
          [Commit SHA]($COMMIT_URL)

          EOF
          )
          echo "$README_CONTENT" >> module_a/README.md
      - name: Print README.md
        run: cat module_a/README.md

      - name: Create Module A
        if: false # Don't run
        run: tfx registry module create -n ${{ env.MODULE_NAME }} -p gcp
      - name: Create Module A
        working-directory: ./module_a
        run: tfx registry module version create -n ${{ env.MODULE_NAME }} -p gcp -v ${{ env.MODULE_VERSION }}
